const htmlMinifier = require("html-minifier-terser");
const { readFile, copy, writeFile } = require("fs-extra");

(async () => {
  // Copy /src into /dist
  await copy("src", "dist");

  // Minify index.html
  const html = (await readFile("dist/index.html")).toString();

  const htmlMinified = await htmlMinifier.minify(html, {
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    includeAutoGeneratedTags: true,
    removeAttributeQuotes: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortClassName: true,
    useShortDoctype: true,
    collapseWhitespace: true,
  });

  await writeFile("dist/index.html", htmlMinified);
})();
